config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  resources :users, only: [:show,:edit,:update,:index]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/concerns/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/book.rb
class Book < ApplicationRecord
     belongs_to :user, optional: true
     has_many :book_comments, dependent: :destroy
     has_many :favorites, dependent: :destroy

     def favorited_by?(user)
         favorites.where(user_id: user.id).exists?
     end


validates :title, presence: true
validates :body, presence: true, length: {maximum: 200}


end

app/models/concerns/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 validates :name, uniqueness: true , presence: true, length: {in: 2..20}
 validates :introduction, length:{maximum: 50}

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    root_oath
  end
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book=Book.find(params[:book_id])
    @book_comment=current_user.book_comments.new(book_comment_params)
    @book_comment.book_id=@book.id
    if @book_comment.save

      redirect_to book_path(@book)
    else
      @newbook=Book.new
      @user=@book.user
      render 'books/show'
    end

  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book=Book.new
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice]="You created book successfully."
      redirect_to book_path(@book.id)
    else
      @user=current_user
      @books=Book.all
      render :index
    end
  end

  def index
    @user=current_user

    @book=Book.new


    @books=Book.all

  end

  def show
    @newbook=Book.new
    @book=Book.find(params[:id])
    @user=@book.user
    @book_comment=BookComment.new

  end

  def edit
    @book =Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book=Book.find(params[:id])
    @book.user_id=current_user.id
    if @book.update(book_params)
      flash[:notice] ="Book was successfully updated"
    redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end


  def destroy
    @book=Book.find(params[:id])

    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
     book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
    @book=Book.new

    @books=Book.where(user_id: @user.id)
  end

  def index
      @user = current_user
      @users=User.all
      @book=Book.new
      @books=Book.all
  end

  def edit
   @user=User.find(params[:id])
   if @user == current_user
         render "edit"
   else
    redirect_to user_path(current_user)
   end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] ="Book was successfully updated"
     redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<%if model.errors.any? %>
<div class="error">
<h2><%= model.errors.count %>errors prohibited this obj from being saved</h2>
<ul>
  <% model.errors.full_massages.each do |message| %>
  <li class="error-message"><%= message %></li>
  <%end%>
</ul>
</div>
<%end%>

app/views/books/_list.html.erb
<h1>New book</h1>
<%= form_with model: book, local:true do |f| %>
<h4>title</h4>
<%= f.text_field :title %>
<h4>Opnion</h4>
<%= f.text_area :body %></br>

<%= f.submit 'Create Book', class:'btn btn-success' %>

<%end%>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-6.offset-md-3">

<h1>Editing Book</h1>

<%if @book.errors.any? %>
<div class="error">
<h2><%= @book.errors.count %>errors prohibited this obj from being saved</h2>
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li class="error-message"><%= message %></li>
  <%end%>
</ul>
</div>
<%end%>
<%= form_with model: @book,local:true do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>
<h4>Body</h4>
<%= f.text_area :body %>
</br>
<%= f.submit 'Update Book' %>
<%end%>
<%= link_to "Show",book_path(@book) %>
<%= link_to "Back",books_path %>

</div>
</div>

app/views/books/index.html.erb
<div class="container">
    <div class="row">



          <%if @book.errors.any? %>
          <div class="error">
           <h2><%= @book.errors.count %>errors prohibited this obj from being saved</h2>
           <ul>
           <% @book.errors.full_messages.each do |message| %>
           <li class="error-message"><%= message %></li>
            <%end%>
           </ul>
          </div>
          <%end%>
        <div class="col-md-3">
          <%= render 'users/list', user:@user %>
          <%= render 'books/list', book:@book %>
        </div>
        <div class="col-md-8 offset-md-1">
         <h1>Books</h1>
         <table class="table book-index">
         <thead>
            <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            </tr>
         </thead>

         <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user) do%>
            <%= attachment_image_tag book.user, :profile_image, :fill,50,50,fallback: "no_image.jpg" %>
            <%end%>

            </td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>
               <% if book.favorited_by?(current_user) %>
               <p>
               <%= link_to book_favorites_path(book), method: :delete do %>
               <i class="fas fa-heart heart-red"></i><%= book.favorites.count %>
               <% end %>
               </p>
               <% else %>
               <p>
               <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fas fa-heart heart-blue"></i><%= book.favorites.count %>
               <% end %>
               </p>
               <% end %>
            </td>

            <td><p>コメント件数：<%= book.book_comments.count %></p></td>

           </tr>
           <% end%>
         </tbody>
         </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
   <div class="container">
    <div class="row">

       
        <%if @book.errors.any? %>
        <div class="error">
         <h2><%= @book.errors.count %>errors prohibited this obj from being saved</h2>
        <ul>
           <% @book.errors.full_messages.each do |message| %>
           <li class="error-message"><%= message %></li>
           <%end%>
        </ul>
        </div>
        <%end%>
        <div class="col-md-3 ">
          <%= render 'users/list', user:@user %>
          <%= render 'books/list', book:@newbook %>
        </div>
        <div class="col-md-8 offset-md-1">
        <h1>Book detail</h1>
          <table class="table table-user-show">



            <tr>
            <td><%= link_to user_path(@user) do %>
            <%=attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg"  %></td>
            <%= link_to @user.name,user_path(@user) %>
            <%end%>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <td>
               <% if @book.favorited_by?(current_user) %>
               <p>
               <%= link_to book_favorites_path(@book), method: :delete do %>
               <i class="fas fa-heart heart-red"></i><%= @book.favorites.count %>
               <% end %>
               </p>
               <% else %>
               <p>
               <%= link_to book_favorites_path(@book), method: :post do %>
                <i class="fas fa-heart heart-blue"></i><%= @book.favorites.count %>
               <% end %>
               </p>
               <% end %>
            </td>
            <td><p>コメント件数：<%= @book.book_comments.count %></p></td>
            <% if @book.user == current_user %>
                <td><%= link_to "Edit",edit_book_path(@book),class: 'btn btn-success' %></td>
                <td><%= link_to "Destroy",book_path(@book) ,method: :delete,class: 'btn btn-danger', "data-confirm"=>"Are you sure?" %></td>
              <% end%>

            </tr>


          </table>
            <div class="comments">

               <% @book.book_comments.each do |book_comment| %>
                <%= link_to user_path(book_comment.user) do %>
                <%=attachment_image_tag book_comment.user, :profile_image, :fill, 10, 10, fallback: "no_image.jpg"  %></td>
                <%= link_to book_comment.user.name,user_path(book_comment.user) %>
                 <%end%>

             <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
             <% if book_comment.user == current_user %>
             <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment), method: :delete,class: 'btn btn-danger' %>
             <%end%>
             <%end%>
          </div>
          <%if @book_comment.errors.any? %>
          <div class="error">
            <h2><%= @book_comment.errors.count %>errors prohibited this obj from being saved</h2>
             <ul>
               <% @book_comment.errors.full_messages.each do |message| %>
                  <li class="error-message"><%= message %></li>
                <%end%>
              </ul>
          </div>
          <%end%>
          <div class="new-comment">
            <%= form_with(model:[@book,@book_comment],local: true)do |f|%>
            <%= f.text_area :comment %></br>
            <%= f.submit "送信" %>
            <%end%>
          </div>
        </div>

app/views/homes/about.html.erb
<h1 class="text-center">Welcom to <i class="fas fa-book"></i>Bookers!</h1>

app/views/homes/top.html.erb
<div class="text-center">
<h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
<p>in <i class="fas fa-book"></i>Bookers,</br>you can share and exchange youer opinions, inpressions, </br>and emotions</p>

<p>about various books!</p>

<%= link_to "Log in", new_user_session_path, class: "btn btn-info w-120px mt-2 " %></br>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success w-120px mt-2"  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand p-3" href="/"><i class="fas fa-book"></i>Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
 <div class="collapse navbar-collapse" id="navbarNavDropdown">
   <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
      <li class="nav-item">
         <%= link_to  user_path(current_user.id), class: 'nav-list text-light p-3' do %><i class="fas fa-home"></i>Home<%end%>

      </li>
      <li class="nav-item">
        <%= link_to  users_path, class: 'nav-list text-light p-3'  do%><i class="fas fa-users"></i>Users<%end%>
      </li>
      <li class="nav-item">
        <%= link_to books_path, class: 'nav-list text-light p-3' do%><i class="fas fa-book-open"></i>Books<%end%>
      </li>
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-list text-light p-3' do%><i class="fas fa-sign-out-alt"></i>Logout<%end%>
      </li>
    <% else %>
      <li class="nav-item">
        <a class= "nav-list text-light p-3" href="/"><i class="fas fa-home"></i>Home</a>
      </li>
      <li class="nav-item">
        <a class= 'nav-list text-light p-3' href="/home/about" ><i class="fas fa-link"></i>About</a>
      </li>
      <li class="nav-item">
        <%= link_to  new_user_registration_path, class: 'nav-list text-light p-3' do %><i class="fas fa-user-plus"></i>sign up<%end%>
      </li>

      <li class="nav-item">
        <%= link_to  new_user_session_path, class: 'nav-list text-light p-3' do%><i class="fas fa-sign-in-alt"></i>login<%end%>
      </li>
    <% end %>
    </ul>
    </div>
    </div>
    </nav>
    </header>
    <main class="body">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    </main>
    <footer>
      <p class="text-center p-30-0">CopyRight Infratop.inc</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_list.html.erb
<h1>User Info</h1>
<table class="profile-container table table-striped">
  <thead>
    <tr>
     <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Name</th>
      <th class="profile-name"><%= user.name %></th>
    </tr>
    <tr>
      <th>Introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <% if @user == current_user %>


      <th class="btn btn-light w-100"><%= link_to  edit_user_path(current_user)  do %><i class="fas fa-user-cog"></i><%end%></th>
      <% else %>
      <th class="btn btn-light w-100"><%= link_to  edit_user_path(@user.id) do %><i class="fas fa-user-cog"></i><%end%></th>
      <% end%>
    </tr>
  </tbody>



</table>

app/views/users/edit.html.erb
 <div class="row">
   <div class="col-md-3">
 <h1>User Info</h1>

<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
<div class="error">
<h2><%= @user.errors.count %>errors prohibited this obj from being saved</h2>
<ul>
  <% @user.errors.full_messages.each do |message| %>
  <li class="error-message"><%= message %></li>
  <%end%>
</ul>
</div>
<%end%>
<p>Name</p>
<%= f.text_field :name %>
<p>Image</p>
<%= f.attachment_field :profile_image %>
<p>Introduction</p>
<%= f.text_area :introduction %></br>
<%= f.submit "Update User",class:"btn btn-success" %>
<%end%>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-3 ">
  <%= render 'users/list', user: @user %>
  <%= render 'books/list', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h1>Users</h1>
   <table class="table table-sm user-index">
    <thead>
    <th>image</th>
    <th>name</th>
    <th></th>
     </thead>
     <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 10,10,fallback:"no_image.jpg"%></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show","/users/#{user.id}" %></td>
    </tr>
    <%end%>
      </tbody>
     </table>
  </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3 ">
         <%= render 'users/list', user:@user %>
         <%= render 'books/list', book:@book %>
        </div>
        <div class="col-md-8 offset-md-1 ">
         <h1>Book detail</h1>
         <table class="table table-user-show">
            <% @books.each do |book| %>
          <tr>
              <td>
                <%= link_to user_path(@user) do%>
                <%= attachment_image_tag @user, :profile_image, :fill, 50,50, fallback: "no_image.jpg" %>
                <% end%>
              </td>
              <td><%=link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
               <% if book.favorited_by?(current_user) %>
               <p>
               <%= link_to book_favorites_path(book), method: :delete do %>
               <i class="fas fa-heart heart-red"></i><%= book.favorites.count %>
               <% end %>
               </p>
               <% else %>
               <p>
               <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fas fa-heart heart-blue"></i><%= book.favorites.count %>
               <% end %>
               </p>
               <% end %>
            </td>

            <td><p>コメント件数：<%= book.book_comments.count %></p></td>

                <% if book.user == current_user %>
                <td><%= link_to "Edit",edit_book_path(book),class: 'btn btn-success' %></td>
                <td><%= link_to "Destroy",book_path(book) ,method: :delete,class: 'btn btn-danger', "data-confirm"=>"Are you sure?" %></td>
                <% end%>
          </tr>
           <%end%>


         </table>
        </div>
    </div>
    </div>